# Generated by Django 4.1.5 on 2023-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=255, verbose_name='Имя')),
                ('image_user', models.ImageField(upload_to='users', verbose_name='Фотография пользователя')),
                ('email_user', models.EmailField(max_length=254, verbose_name='Почта')),
                ('message_user', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
