# Generated by Django 4.1.5 on 2023-01-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='О нас')),
                ('descriptions', models.TextField(verbose_name='Описание о нас')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Первая фотография о нас')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Вторая фотография о нас')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Третья фотография о нас')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Четвертая фотография о нас')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Пятая фотография о нас')),
            ],
            options={
                'verbose_name': 'Настройка О нас',
                'verbose_name_plural': 'Настройки О нас',
            },
        ),
    ]
