# Generated by Django 4.1.5 on 2023-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_backroundindex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackroundIndex',
            new_name='BackroundAbout',
        ),
    ]
