# Generated by Django 4.1.5 on 2023-02-05 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_backroundindex_backroundabout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image5',
        ),
        migrations.CreateModel(
            name='ImageAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Фотография о нас')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='about.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Добавить фотографию  О нас',
                'verbose_name_plural': 'Добавить фотографию О нас',
            },
        ),
    ]
