# Generated by Django 4.1.5 on 2023-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефонный номер')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочие дни')),
                ('work2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочое время')),
                ('address_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на адрес')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на instagram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на WhatsApp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на Telegram')),
            ],
            options={
                'verbose_name': 'Настройка Контакта',
                'verbose_name_plural': 'Настройки Контактов',
            },
        ),
    ]
