# Generated by Django 4.1.5 on 2023-01-30 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_address_url_contact_youtube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='telegram',
        ),
    ]
