# Generated by Django 4.1.5 on 2023-01-30 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='telegram',
        ),
    ]
