# Generated by Django 4.1.5 on 2023-01-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_contact_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackroundContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backround/', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Задний фон страницы <<Контакты>>',
                'verbose_name_plural': 'Задний фон страницы <<Контакты>>',
            },
        ),
    ]
