# Generated by Django 4.1.5 on 2023-02-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackroundRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backround/', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Задний фон страницы <<Наш Блог>>',
                'verbose_name_plural': 'Задний фон страницы  <<Наш Блог>>',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='О номере')),
                ('descriptions', models.TextField(verbose_name='Описание о номере')),
                ('blog_time', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Первая фотография номера')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Вторая фотография номера')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Третья фотография номера')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Четвертая фотография номера')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Пятая фотография номера')),
            ],
            options={
                'verbose_name': 'Настройка Блога',
                'verbose_name_plural': 'Настройки Новостей',
            },
        ),
    ]
