# Generated by Django 4.1.5 on 2023-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_backroundroom_backroundblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='descriptions',
            field=models.TextField(verbose_name='Описание о Блоге'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Первая фотография блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Вторая фотография блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Третья фотография блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Четвертая фотография блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Пятая фотография блога'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='О Блоге'),
        ),
    ]
