# Generated by Django 4.1.5 on 2023-02-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_image1_remove_blog_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Наш Блог', 'verbose_name_plural': 'Наши Новости'},
        ),
        migrations.AlterModelOptions(
            name='imageblog',
            options={'verbose_name': 'Добавить фотографию для блога', 'verbose_name_plural': 'Добавить фотографию для блога'},
        ),
    ]
