# Generated by Django 4.1.5 on 2023-02-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_options_alter_imageblog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageblog',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_blog', to='blog.blog', verbose_name='Выберите блог'),
        ),
    ]
