# Generated by Django 4.1.5 on 2023-01-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название слайда')),
                ('descriptions', models.TextField(verbose_name='Описание для слайда')),
                ('image', models.ImageField(upload_to='slide/', verbose_name='Фотография для слайда')),
            ],
            options={
                'verbose_name': 'Настройка слайда',
                'verbose_name_plural': 'Настройки слайда',
            },
        ),
    ]
