# Generated by Django 4.1.5 on 2023-01-30 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_backroundindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackroundIndex',
        ),
    ]
