# Generated by Django 4.1.5 on 2023-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Назваие партнера'),
            preserve_default=False,
        ),
    ]
