# Generated by Django 4.1.5 on 2023-02-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_partners_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=255, verbose_name='Клиетов')),
                ('team', models.CharField(max_length=255, verbose_name='Сотрудников')),
                ('star', models.CharField(max_length=255, verbose_name='Звезды хостела')),
                ('room', models.ImageField(upload_to='number', verbose_name='Фотография комнаты')),
                ('cook', models.ImageField(upload_to='number', verbose_name='Фотография кухни')),
                ('game', models.ImageField(upload_to='number', verbose_name='Фотография Игровой зоны')),
                ('conference', models.ImageField(upload_to='number', verbose_name='Фотография Конференц зала')),
            ],
        ),
    ]
