# Generated by Django 4.1.5 on 2023-02-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'Мы в числах', 'verbose_name_plural': 'Мы в числах'},
        ),
    ]
