# Generated by Django 4.1.5 on 2023-02-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackroundTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backround/', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Задний фон страницы <<Наша команда>>',
                'verbose_name_plural': 'Задний фон страницы <<Наша комана>>',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team', verbose_name='Фотография сотрудника')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя сотрудника')),
                ('work', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность сотрудника')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram сотрудника')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name=' Whatsapp сотрудника')),
                ('Facebook', models.URLField(blank=True, null=True, verbose_name='Facebook  сотрудника')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
            },
        ),
    ]
