# Generated by Django 4.1.5 on 2023-01-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackroundRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backround/', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Задний фон страницы <<Наши номера>>',
                'verbose_name_plural': 'Задний фон страницы  <<Наши номера>>',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='О номере')),
                ('descriptions', models.TextField(verbose_name='Описание о номере')),
                ('price', models.CharField(max_length=255, verbose_name='Цена номера')),
                ('service', models.CharField(max_length=255, verbose_name='Оценка услуг от 1 до 5')),
                ('comfort', models.CharField(max_length=255, verbose_name='Оценка комфорта от 1 до 5')),
                ('location', models.CharField(max_length=255, verbose_name='Оценка локации от 1 до 5')),
                ('amenities1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первое удобство')),
                ('amenities2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Второе удобство')),
                ('amenities3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Третье удобство')),
                ('amenities4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Четвертое удобство')),
                ('amenities5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пятое удобство')),
                ('amenities6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Шестое удобство')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Первая фотография номера')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Вторая фотография номера')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Третья фотография номера')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Четвертая фотография номера')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Пятая фотография номера')),
            ],
            options={
                'verbose_name': 'Настройка номера',
                'verbose_name_plural': 'Настройки Номеров',
            },
        ),
    ]
