# Generated by Django 4.1.5 on 2023-01-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_location_room_clean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='clean',
            new_name='location',
        ),
    ]
