# Generated by Django 4.1.5 on 2023-02-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name': 'Комментрии к номерам', 'verbose_name_plural': 'Комментрии к номерам'},
        ),
    ]
