# Generated by Django 4.1.5 on 2023-02-05 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Наш номер', 'verbose_name_plural': 'Наши Номера'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='amenities6',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image5',
        ),
        migrations.CreateModel(
            name='ImageRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Фотография номера')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_room', to='rooms.room', verbose_name='Выберите номер')),
            ],
            options={
                'verbose_name': 'Настройка номера',
                'verbose_name_plural': 'Настройки Номеров',
            },
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Удобство номера')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='rooms.room', verbose_name='Выберите номер')),
            ],
            options={
                'verbose_name': 'Добавить удобство для номера',
                'verbose_name_plural': 'Добавить удобство для номера',
            },
        ),
    ]
