# Generated by Django 4.1.5 on 2023-02-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_options_remove_room_amenities1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Фотография номера'),
        ),
    ]
