# Generated by Django 4.1.5 on 2023-02-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='room_image', verbose_name='Фотография номера'),
        ),
    ]
