# Generated by Django 4.1.5 on 2023-02-05 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_room_image_room_image1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageroom',
            options={'verbose_name': 'Добавить фотографию для номера', 'verbose_name_plural': 'Добавить фотографию для номера'},
        ),
    ]
